name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main  # ou o nome do seu branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar acesso SSH com chave .pem
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Fazer deploy para a instância EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/flask-app  # altere se for outro caminho
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart flaskapp
          EOF

